### ISSUE TITLE
Slow training

### ISSUE THREAD

**Issue by lynetcha** [hxdengBerkeley/PointCNN.Pytorch#1]
Thanks for the great implementation! I notice training is quite slow. Any pointers on what part of the code can be optimized for speed?

**Comment by lynetcha** [comment]
Nevermind. I found the note about KNN. Thanks!

**Comment by iSarmad** [comment]
hello, can you suggest how to improve training time?, it takes excruciatingly long at the moment uses only 10 to 15 % of GPU resources, thanks
